version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
        - echo Installing kubectl tool...
        - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
        - chmod +x ./kubectl
        - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
    pre_build:
        commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 555516925462.dkr.ecr.us-west-1.amazonaws.com
        - REPOSITORY_URI=555516925462.dkr.ecr.us-west-1.amazonaws.com/nodejsapp
        - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
        - echo Logging in to Amazon EKS...
        - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
    build:
        commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker build -t $REPOSITORY_URI:latest .
        - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG   
    post_build:
        commands:
        - echo Pushing the Docker images...
        - docker push $REPOSITORY_URI:latest
        - echo Writing image definitions file...
        - printf '[{"name":"cicd-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG
        - echo deploy the latest image on EKS cluster...
        - kubectl apply -f deployment.yml
        - kubectl apply -f service.yml
artifacts:
    files:
        - '**/*'